---
topics:
        # Presently gobmp does not generate messages of these types:
        # collector:         "gobmp.parsed.collector"
        # router:            "gobmp.parsed.router"
        #
        # Topics below can use the following variable in their names:
        #   {{router_ip}}, {{named_router}}, {{peer_ip} and {{peer_asn}}
        # {{named_router}} specifically is determined via the "named_routers" section
        # (see below)
        stats:             "gobmp.parsed.statistics"
        peer:              "gobmp.parsed.peer"
        raw:               "gobmp.bmp_raw"
        unicast_prefix:    "gobmp.parsed.unicast_prefix"
        unicast_prefix_v4: "gobmp.parsed.unicast_prefix_v4"
        unicast_prefix_v6: "gobmp.parsed.unicast_prefix_v6"
        ls_node:           "gobmp.parsed.ls_node"
        ls_link:           "gobmp.parsed.ls_link"
        ls_prefix:         "gobmp.parsed.ls_prefix"
        l3vpn:             "gobmp.parsed.l3vpn"
        l3vpn_v4:          "gobmp.parsed.l3vpn_v4"
        l3vpn_v6:          "gobmp.parsed.l3vpn_v6"
        evpn:              "gobmp.parsed.evpn"
        ls_srv6_sid:       "gobmp.parsed.ls_srv6_sid"
        sr_policy:         "gobmp.parsed.sr_policy"
        sr_policy_v4:      "gobmp.parsed.sr_policy_v4"
        sr_policy_v6:      "gobmp.parsed.sr_policy_v6"
        flowspec:          "gobmp.parsed.flowspec"
        flowspec_v4:       "gobmp.parsed.flowspec_v4"
        flowspec_v6:       "gobmp.parsed.flowspec_v6"

named_routers:
  - name: fallback
    matches:
      - 0.0.0.0/0
      - ::/0
